# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'easerPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core', '~> 6.2.0'

  target 'easerPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'easerPod-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for easerPod-tvOS

  target 'easerPod-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
